### ISSUE TITLE
Suggestions for technical improvements 

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/data-entry-app#133]
After the first release of this app, we need to probably take some time to refactor some parts of this app. This GitHub issue can be a place where we collect things we would like to see improved. We can comment here about things that need to be optimised, parts of the code that are hard to work with, or need better test coverage. If you already have a solution, or a global direction of how to address the problem in mind, please include that in the comment.

**Comment by HendrikThePendric** [comment]
We should probably add a state library like redux so we can have all the application state in one place and are able to subscribe to "slices" of this state in components.

**Comment by HendrikThePendric** [comment]
We should probably introduce a `DataEntryFormInstanceProvider` to which we pass a the current react-final-form `Form` instance. This way the entire application can easily interact with the form and its individual fields using the [FormApi](https://final-form.org/docs/final-form/types/FormApi). I think that some of the providers we currently have could probably be removed if we had this, and we can also reduce the amount of re-renders this way (I am mainly thinking about using `form.registerField` and `form.subscribe` to do this).

**Comment by HendrikThePendric** [comment]
We could switch to [final-form-calculate](https://github.com/final-form/final-form-calculate) for indicators and totals

**Comment by HendrikThePendric** [comment]
We should look into ways of make the `useDataValues()` hook return a `data` object that changes less frequently. Potentially we could use this [structural sharing](https://tkdodo.eu/blog/react-query-render-optimizations#structural-sharing) approach to achieve that goal.

**Comment by HendrikThePendric** [comment]
From the perspective of the data entry fields (i.e. the inputs), it would make a lot of sense if all the entire form state was provided by react-final-form. We could take the following approach to achieve this:
- Allow other parts of the app to interact with the form by using the aforementioned `DataEntryFormInstanceProvider` provider
- Use a RFF `Field`s `data` prop to store information needed by the field, but not strictly speaking part of a form field. For example sync status etc.
- Use add `mutators` to the RFF `Form` which allow updating these meta fields (aka the `data` prop).

This way, we can easily update individual fields from the `useQuey` hooks and we can keep all field data in a single place. I think this would help a lot.

**Comment by Birkbjo** [comment]
> From the perspective of the data entry fields (i.e. the inputs), it would make a lot of sense if the entire form-field state was provided by react-final-form. We could take the following approach to achieve this:
Allow other parts of the app to interact with the form by using the aforementioned DataEntryFormInstanceProvider provider
Use a RFF Fields data prop to store information needed by the field, but not strictly speaking part of a form field. For example sync status etc.
Use add mutators to the RFF Form which allow updating these meta fields (aka the data prop).
This way, we can easily update individual fields from the useQuey hooks and we can keep all field data in a single place. I think this would help a lot.

If we get structural sharing to work properly I don't think this is necessary. Then `react-query` would be the only source of truth (except for form-state). And we could use `useQuery`-targetting specific fields without worrying about re-rendering.

I haven't fully investigated how this works, or if it does. I just think that if it works the way I hope - we don't have to deal with these points at all. Each field could just `useQuery` and select the part of the cache it wants.

**Comment by HendrikThePendric** [comment]
Moving this to a discussion here https://github.com/dhis2/data-entry-app/discussions/134
